### ISSUE TITLE
爬虫代码存在问题

### ISSUE THREAD

**Issue by luckydog-001** [Yanyaoli/douban#1]
作者您好，爬取豆瓣基本信息的代码中只能爬取一页，我试着改为了range（0，250，25）可以爬取，但是爬取详细信息一直出错，cookie应该如何添加呢？

**Comment by yanyaoli** [comment]
> 作者您好，爬取豆瓣基本信息的代码中只能爬取一页，我试着改为了range（0，250，25）可以爬取，但是爬取详细信息一直出错，cookie应该如何添加呢？

对呢，默认写的爬取第一页，点击爬取详情信息好像就有cookie输入框。

**Comment by luckydog-001** [comment]
感谢作者，但是我不知道cookie如何获取，请问如何获取豆瓣的cookie呢？爬取详细信息出错是因为cookie问题吗

**Comment by yanyaoli** [comment]
> 感谢作者，但是我不知道cookie如何获取，请问如何获取豆瓣的cookie呢？爬取详细信息出错是因为cookie问题吗

![image](https://github.com/user-attachments/assets/81807702-49d3-4fcd-95a4-4d073217930d)

[参考](https://blog.csdn.net/qq_16209077/article/details/80012080)
